// constants/mockData.ts
import type { FeaturedWine } from '@/ts/wine';

export const MOCK_FAVORITES_DATA: readonly FeaturedWine[] = [
  {
    id: '1',
    name: 'Château Margaux 2015',
    winery: 'Château Margaux',
    vintage: 2015,
    region: 'Bordeaux, France',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=300&h=400&fit=crop',
    price: 450,
    description: 'A legendary Bordeaux blend showcasing elegance and power in perfect harmony.',
    grapeVariety: ['Cabernet Sauvignon', 'Merlot'],
    color: 'Deep Ruby',
    alcoholContent: 13.5,
    sugarContent: 'Dry',
    taste: ['Black Cherry', 'Cassis', 'Cedar'],
    aroma: ['Violets', 'Graphite'],
    foodPairing: ['Lamb', 'Beef Wellington'],
    reviews: 127,
    sommelierNotes: 'Exceptional vintage with remarkable aging potential.',
  },
  {
    id: '2',
    name: 'Cloudy Bay Sauvignon Blanc',
    winery: 'Cloudy Bay',
    vintage: 2022,
    region: 'Marlborough, New Zealand',
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1558008258-3256797b43f3?w=300&h=400&fit=crop',
    price: 28,
    description: 'Crisp and refreshing with distinctive tropical and citrus flavors.',
    grapeVariety: ['Sauvignon Blanc'],
    color: 'Pale Yellow',
    alcoholContent: 13.0,
    sugarContent: 'Dry',
    taste: ['Passionfruit', 'Lime'],
    aroma: ['Tropical Fruits'],
    foodPairing: ['Seafood', 'Goat Cheese'],
    reviews: 89,
    sommelierNotes: 'Perfect expression of Marlborough terroir.',
  },
  {
    id: '3',
    name: 'Barolo Brunate 2018',
    winery: 'Giuseppe Rinaldi',
    vintage: 2018,
    region: 'Piedmont, Italy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=300&h=400&fit=crop',
    price: 85,
    description: 'Traditional Barolo with complex tannins and exceptional longevity.',
    grapeVariety: ['Nebbiolo'],
    color: 'Garnet Red',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Cherry', 'Rose', 'Tar', 'Truffle'],
    aroma: ['Red Fruits', 'Roses', 'Leather'],
    foodPairing: ['Truffle Dishes', 'Braised Beef', 'Aged Parmesan'],
    reviews: 67,
    sommelierNotes: "A masterpiece from one of Barolo's finest producers.",
  },
  {
    id: '4',
    name: 'Champagne Dom Pérignon 2012',
    winery: 'Dom Pérignon',
    vintage: 2012,
    region: 'Champagne, France',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=300&h=400&fit=crop',
    price: 180,
    description: 'Prestigious champagne with exceptional complexity and finesse.',
    grapeVariety: ['Chardonnay', 'Pinot Noir'],
    color: 'Golden Yellow',
    alcoholContent: 12.5,
    sugarContent: 'Brut',
    taste: ['Citrus', 'Brioche', 'Honey', 'Almonds'],
    aroma: ['White Flowers', 'Yeast', 'Minerals'],
    foodPairing: ['Oysters', 'Caviar', 'Fine Seafood'],
    reviews: 203,
    sommelierNotes: 'Perfect expression of Dom Pérignon house style.',
  },
  {
    id: '5',
    name: 'Opus One 2019',
    winery: 'Opus One',
    vintage: 2019,
    region: 'Napa Valley, USA',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=300&h=400&fit=crop',
    price: 320,
    description: 'Bordeaux-style blend representing the pinnacle of Napa Valley winemaking.',
    grapeVariety: ['Cabernet Sauvignon', 'Merlot', 'Petit Verdot'],
    color: 'Deep Purple',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Blackcurrant', 'Chocolate', 'Espresso', 'Spice'],
    aroma: ['Dark Berries', 'Cedar', 'Vanilla'],
    foodPairing: ['Prime Rib', 'Duck Confit', 'Dark Chocolate'],
    reviews: 134,
    sommelierNotes: 'Collaboration between Mondavi and Rothschild reaches new heights.',
  },
  {
    id: 'scan-1',
    name: 'Caymus Cabernet Sauvignon 2020',
    winery: 'Caymus Vineyards',
    vintage: 2020,
    region: 'Napa Valley, California',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=300&h=400&fit=crop',
    price: 65,
    description:
      'Rich and concentrated Cabernet Sauvignon with dark fruit flavors and smooth tannins.',
    grapeVariety: ['Cabernet Sauvignon'],
    color: 'Deep Purple',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Blackberry', 'Cassis', 'Vanilla'],
    aroma: ['Dark Fruits', 'Cedar'],
    foodPairing: ['Grilled Steak', 'Lamb Chops'],
    reviews: 156,
    sommelierNotes: 'Excellent everyday Cabernet with consistent quality year after year.',
  },
] as const;
