// constants/wineDatabase.ts
import type { FeaturedWine } from '@ts/index';

export const WINE_DATABASE: Record<string, FeaturedWine> = {
  '1': {
    id: '1',
    name: 'Château Margaux 2015',
    winery: 'Château Margaux',
    vintage: 2015,
    region: 'Bordeaux, France',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
    price: 450,
    description:
      "A legendary Bordeaux blend showcasing elegance and power in perfect harmony. This exceptional vintage demonstrates the estate's mastery of terroir expression.",
    grapeVariety: ['Cabernet Sauvignon', 'Merlot', 'Petit Verdot', 'Cabernet Franc'],
    color: 'Deep Ruby',
    alcoholContent: 13.5,
    sugarContent: 'Dry',
    taste: ['Black Cherry', 'Cassis', 'Cedar', 'Tobacco', 'Graphite'],
    aroma: ['Violets', 'Graphite', 'Dark Berries', 'Leather', 'Vanilla'],
    foodPairing: ['Lamb', 'Beef Wellington', 'Aged Cheese', 'Duck Confit'],
    reviews: 127,
    sommelierNotes:
      'Exceptional vintage with remarkable aging potential. The 2015 Château Margaux is a masterpiece that balances power and elegance in extraordinary harmony.',
  },
  'scan-1': {
    id: 'scan-1',
    name: 'Caymus Cabernet Sauvignon 2020',
    winery: 'Caymus Vineyards',
    vintage: 2020,
    region: 'Napa Valley, California',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=400&h=600&fit=crop',
    price: 65,
    description:
      "Rich and concentrated Cabernet Sauvignon with dark fruit flavors and smooth tannins. A signature Napa Valley expression from one of California's most respected producers.",
    grapeVariety: ['Cabernet Sauvignon'],
    color: 'Deep Purple',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Blackberry', 'Cassis', 'Vanilla', 'Oak', 'Dark Chocolate'],
    aroma: ['Dark Fruits', 'Cedar', 'Spice', 'Coffee', 'Tobacco'],
    foodPairing: ['Grilled Steak', 'Lamb Chops', 'Dark Chocolate', 'Aged Cheddar'],
    reviews: 156,
    sommelierNotes:
      'Excellent everyday Cabernet with consistent quality year after year. Perfect introduction to Napa Valley Cabernet Sauvignon.',
  },
  'scan-2': {
    id: 'scan-2',
    name: "Kendall-Jackson Vintner's Reserve Chardonnay",
    winery: 'Kendall-Jackson',
    vintage: 2021,
    region: 'California, USA',
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1558008258-3256797b43f3?w=400&h=600&fit=crop',
    price: 18,
    description:
      "Balanced Chardonnay with tropical fruit flavors and a hint of oak. Masterfully crafted to showcase the best of California's diverse vineyard sites.",
    grapeVariety: ['Chardonnay'],
    color: 'Golden Yellow',
    alcoholContent: 13.5,
    sugarContent: 'Dry',
    taste: ['Pineapple', 'Pear', 'Vanilla', 'Butter', 'Green Apple'],
    aroma: ['Tropical Fruits', 'Citrus', 'Oak', 'Honey', 'Minerals'],
    foodPairing: ['Roasted Chicken', 'Seafood', 'Creamy Pasta', 'Lobster'],
    reviews: 203,
    sommelierNotes:
      'A reliable crowd-pleaser with perfect balance of fruit and oak. Exemplifies the California Chardonnay style.',
  },
  '2': {
    id: '2',
    name: 'Cloudy Bay Sauvignon Blanc',
    winery: 'Cloudy Bay',
    vintage: 2022,
    region: 'Marlborough, New Zealand',
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1558008258-3256797b43f3?w=400&h=600&fit=crop',
    price: 28,
    description: 'Crisp and refreshing with distinctive tropical and citrus flavors.',
    grapeVariety: ['Sauvignon Blanc'],
    color: 'Pale Yellow',
    alcoholContent: 13.0,
    sugarContent: 'Dry',
    taste: ['Passionfruit', 'Lime', 'Gooseberry'],
    aroma: ['Tropical Fruits', 'Fresh Herbs'],
    foodPairing: ['Seafood', 'Goat Cheese', 'Asian Cuisine'],
    reviews: 89,
    sommelierNotes: 'Perfect expression of Marlborough terroir.',
  },
  '3': {
    id: '3',
    name: 'Barolo Brunate 2018',
    winery: 'Giuseppe Rinaldi',
    vintage: 2018,
    region: 'Piedmont, Italy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
    price: 85,
    description: 'Traditional Barolo with complex tannins and exceptional longevity.',
    grapeVariety: ['Nebbiolo'],
    color: 'Garnet Red',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Cherry', 'Rose', 'Tar', 'Truffle'],
    aroma: ['Red Fruits', 'Roses', 'Leather'],
    foodPairing: ['Truffle Dishes', 'Braised Beef', 'Aged Parmesan'],
    reviews: 67,
    sommelierNotes: "A masterpiece from one of Barolo's finest producers.",
  },
  '4': {
    id: '4',
    name: 'Champagne Dom Pérignon 2012',
    winery: 'Dom Pérignon',
    vintage: 2012,
    region: 'Champagne, France',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    price: 180,
    description: 'Prestigious champagne with exceptional complexity and finesse.',
    grapeVariety: ['Chardonnay', 'Pinot Noir'],
    color: 'Golden Yellow',
    alcoholContent: 12.5,
    sugarContent: 'Brut',
    taste: ['Citrus', 'Brioche', 'Honey', 'Almonds'],
    aroma: ['White Flowers', 'Yeast', 'Minerals'],
    foodPairing: ['Oysters', 'Caviar', 'Fine Seafood'],
    reviews: 203,
    sommelierNotes: 'Perfect expression of Dom Pérignon house style.',
  },
  '5': {
    id: '5',
    name: 'Opus One 2019',
    winery: 'Opus One',
    vintage: 2019,
    region: 'Napa Valley, USA',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&h=600&fit=crop',
    price: 320,
    description: 'Bordeaux-style blend representing the pinnacle of Napa Valley winemaking.',
    grapeVariety: ['Cabernet Sauvignon', 'Merlot', 'Petit Verdot'],
    color: 'Deep Purple',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Blackcurrant', 'Chocolate', 'Espresso', 'Spice'],
    aroma: ['Dark Berries', 'Cedar', 'Vanilla'],
    foodPairing: ['Prime Rib', 'Duck Confit', 'Dark Chocolate'],
    reviews: 134,
    sommelierNotes: 'Collaboration between Mondavi and Rothschild reaches new heights.',
  },
  '6': {
    id: '6',
    name: 'Caymus Cabernet Sauvignon 2020',
    winery: 'Caymus Vineyards',
    vintage: 2020,
    region: 'Napa Valley, USA',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1566995349570-e27b96a0b3f1?w=400&h=600&fit=crop',
    price: 85,
    description:
      "Rich and concentrated Cabernet Sauvignon with dark fruit flavors and smooth tannins. A signature Napa Valley expression from one of California's most respected producers.",
    grapeVariety: ['Cabernet Sauvignon'],
    color: 'Deep Purple',
    alcoholContent: 14.5,
    sugarContent: 'Dry',
    taste: ['Blackberry', 'Cassis', 'Vanilla', 'Oak', 'Dark Chocolate'],
    aroma: ['Dark Fruits', 'Cedar', 'Spice', 'Coffee', 'Tobacco'],
    foodPairing: ['Grilled Steak', 'Lamb Chops', 'Dark Chocolate', 'Aged Cheddar'],
    reviews: 156,
    sommelierNotes:
      'Excellent everyday Cabernet with consistent quality year after year. Perfect introduction to Napa Valley Cabernet Sauvignon.',
  },
  '7': {
    id: '7',
    name: 'Veuve Clicquot Brut',
    winery: 'Veuve Clicquot',
    vintage: 2018,
    region: 'Champagne, France',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1504281623087-1a78e7fb75ad?w=400&h=600&fit=crop',
    price: 65,
    description:
      'The iconic yellow-labeled champagne with exceptional finesse and elegance. A perfect balance of strength and silkiness, with a distinctive blend of three grape varieties.',
    grapeVariety: ['Pinot Noir', 'Chardonnay', 'Pinot Meunier'],
    color: 'Golden Yellow',
    alcoholContent: 12.0,
    sugarContent: 'Brut',
    taste: ['Citrus', 'Green Apple', 'Brioche', 'Honey', 'Almonds'],
    aroma: ['White Flowers', 'Fresh Bread', 'Minerals', 'Citrus Zest'],
    foodPairing: ['Oysters', 'Sushi', 'Fresh Seafood', 'Soft Cheeses'],
    reviews: 203,
    sommelierNotes:
      'The signature champagne that embodies the Veuve Clicquot style - bold, elegant, and consistently exceptional.',
  },
} as const;
